# Generated by Django 2.0.2 on 2018-04-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('ip_address', models.CharField(blank=True, max_length=50)),
                ('magnet_link', models.TextField()),
            ],
        ),
    ]
