# Generated by Django 2.0.2 on 2018-04-15 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Document',
        ),
    ]
