# Generated by Django 2.0.4 on 2018-04-15 16:17

from django.db import migrations, models
import editor.models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_auto_20180415_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='secret_id',
            field=models.CharField(db_index=True, default=editor.models.generate_secret_id, max_length=32),
        ),
    ]
