# Generated by Django 2.0.2 on 2018-04-15 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_document_secret_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='title',
        ),
    ]
