# Generated by Django 2.0.4 on 2018-04-28 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0005_auto_20180422_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='title',
        ),
    ]
